name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    name: My first job
    runs-on: self-hosted
    steps:
      - name: terraform init
        run: terraform init 
        

